
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DatabaseFirst
{

using System;
    using System.Collections.Generic;
    
public partial class lexicology
{

    public int id { get; set; }

    public Nullable<int> id_word1 { get; set; }

    public Nullable<int> id_word2 { get; set; }

    public Nullable<int> id_comment { get; set; }



    public virtual comment comment { get; set; }

    public virtual word word { get; set; }

    public virtual word word1 { get; set; }

}

}
