
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DatabaseFirst
{

using System;
    using System.Collections.Generic;
    
public partial class lexicAll
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public lexicAll()
    {

        this.syll_mirror = new HashSet<syll_mirror>();

    }


    public int id { get; set; }

    public Nullable<int> lexic_1_2 { get; set; }

    public Nullable<int> lexic_2_3 { get; set; }

    public Nullable<int> lexic_1_3 { get; set; }

    public Nullable<int> lexic_3_4 { get; set; }

    public Nullable<int> lexic_2_4 { get; set; }

    public Nullable<int> lexic_1_4 { get; set; }



    public virtual lexic lexic { get; set; }

    public virtual lexic lexic1 { get; set; }

    public virtual lexic lexic2 { get; set; }

    public virtual lexic lexic3 { get; set; }

    public virtual lexic lexic4 { get; set; }

    public virtual lexic lexic5 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<syll_mirror> syll_mirror { get; set; }

}

}
