
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DatabaseFirst
{

using System;
    using System.Collections.Generic;
    
public partial class lexicIds_view
{

    public int id_lexicAll { get; set; }

    public Nullable<int> lexic_1_2 { get; set; }

    public Nullable<int> lexic_2_3 { get; set; }

    public Nullable<int> lexic_1_3 { get; set; }

    public Nullable<int> lexic_3_4 { get; set; }

    public Nullable<int> lexic_2_4 { get; set; }

    public Nullable<int> lexic_1_4 { get; set; }

    public Nullable<int> id_lexic { get; set; }

    public int id_exercise { get; set; }

    public Nullable<int> level { get; set; }

}

}
