
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DatabaseFirst
{

using System;
    using System.Collections.Generic;
    
public partial class morphology_view
{

    public int id { get; set; }

    public string word { get; set; }

    public string primary_form { get; set; }

    public Nullable<int> id_morphems { get; set; }

    public string phonetic { get; set; }

    public Nullable<int> id_morphology { get; set; }

    public Nullable<int> num_accent { get; set; }

    public int Expr1 { get; set; }

    public Nullable<int> id_part { get; set; }

    public Nullable<int> odush { get; set; }

    public Nullable<int> naricat { get; set; }

    public Nullable<int> rod { get; set; }

    public Nullable<int> sklonen { get; set; }

    public Nullable<int> chislo { get; set; }

    public Nullable<int> padezh { get; set; }

    public Nullable<int> razryad { get; set; }

    public Nullable<int> forma { get; set; }

    public Nullable<int> stepsrav { get; set; }

    public Nullable<int> prost { get; set; }

    public Nullable<int> kolich { get; set; }

    public Nullable<int> drob { get; set; }

    public Nullable<int> razryadznach { get; set; }

    public Nullable<int> lico { get; set; }

    public Nullable<int> vid { get; set; }

    public Nullable<int> spryazh { get; set; }

    public Nullable<int> vozvrat { get; set; }

    public Nullable<int> perehod { get; set; }

    public Nullable<int> naklon { get; set; }

    public Nullable<int> vremya { get; set; }

    public Nullable<int> deistvit { get; set; }

    public Nullable<int> neizmen { get; set; }

    public Nullable<int> znacobraz { get; set; }

    public Nullable<int> proizvodnost { get; set; }

    public Nullable<int> sochinit { get; set; }

    public string context { get; set; }

    public Nullable<int> upotrebls { get; set; }

    public Nullable<int> razryadpoznach { get; set; }

    public Nullable<int> podrazryad { get; set; }

    public string morphems { get; set; }

    public string name { get; set; }

}

}
