
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DatabaseFirst
{

using System;
    using System.Collections.Generic;
    
public partial class morphem
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public morphem()
    {

        this.words = new HashSet<word>();

    }


    public int id { get; set; }

    public string prefix1 { get; set; }

    public string prefix2 { get; set; }

    public string prefix3 { get; set; }

    public string root1 { get; set; }

    public string root2 { get; set; }

    public string suffix1 { get; set; }

    public string suffix2 { get; set; }

    public string suffix3 { get; set; }

    public string suffix4 { get; set; }

    public string okonchan1 { get; set; }

    public string okonchan2 { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<word> words { get; set; }

}

}
