
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DatabaseFirst
{

using System;
    using System.Collections.Generic;
    
public partial class morphology
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public morphology()
    {

        this.words = new HashSet<word>();

    }


    public int id { get; set; }

    public Nullable<int> id_part { get; set; }

    public Nullable<int> odush { get; set; }

    public Nullable<int> naricat { get; set; }

    public Nullable<int> rod { get; set; }

    public Nullable<int> sklonen { get; set; }

    public Nullable<int> chislo { get; set; }

    public Nullable<int> padezh { get; set; }

    public Nullable<int> razryad { get; set; }

    public Nullable<int> forma { get; set; }

    public Nullable<int> stepsrav { get; set; }

    public Nullable<int> prost { get; set; }

    public Nullable<int> kolich { get; set; }

    public Nullable<int> drob { get; set; }

    public Nullable<int> razryadznach { get; set; }

    public Nullable<int> lico { get; set; }

    public Nullable<int> vid { get; set; }

    public Nullable<int> spryazh { get; set; }

    public Nullable<int> vozvrat { get; set; }

    public Nullable<int> perehod { get; set; }

    public Nullable<int> naklon { get; set; }

    public Nullable<int> vremya { get; set; }

    public Nullable<int> deistvit { get; set; }

    public Nullable<int> neizmen { get; set; }

    public Nullable<int> znacobraz { get; set; }

    public Nullable<int> proizvodnost { get; set; }

    public Nullable<int> sochinit { get; set; }

    public Nullable<int> upotrebls { get; set; }

    public Nullable<int> razryadpoznach { get; set; }

    public Nullable<int> podrazryad { get; set; }



    public virtual chislo chislo1 { get; set; }

    public virtual deistvit deistvit1 { get; set; }

    public virtual drob drob1 { get; set; }

    public virtual forma forma1 { get; set; }

    public virtual kolich kolich1 { get; set; }

    public virtual lico lico1 { get; set; }

    public virtual naklon naklon1 { get; set; }

    public virtual naricat naricat1 { get; set; }

    public virtual neizman neizman { get; set; }

    public virtual odush odush1 { get; set; }

    public virtual padezh padezh1 { get; set; }

    public virtual part part { get; set; }

    public virtual perehod perehod1 { get; set; }

    public virtual podrazryad podrazryad1 { get; set; }

    public virtual proizvodnost proizvodnost1 { get; set; }

    public virtual prost prost1 { get; set; }

    public virtual razryad razryad1 { get; set; }

    public virtual razryadpoznach razryadpoznach1 { get; set; }

    public virtual razryadznach razryadznach1 { get; set; }

    public virtual rod rod1 { get; set; }

    public virtual sklonen sklonen1 { get; set; }

    public virtual sochinit sochinit1 { get; set; }

    public virtual spryazh spryazh1 { get; set; }

    public virtual stepsrav stepsrav1 { get; set; }

    public virtual upotrebl upotrebl { get; set; }

    public virtual vid vid1 { get; set; }

    public virtual vozvrat vozvrat1 { get; set; }

    public virtual vremya vremya1 { get; set; }

    public virtual znacobraz znacobraz1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<word> words { get; set; }

}

}
