
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DatabaseFirst
{

using System;
    using System.Collections.Generic;
    
public partial class nextView
{

    public int id_exercise { get; set; }

    public int id_part { get; set; }

    public int id { get; set; }

    public Nullable<int> id_word { get; set; }

    public Nullable<int> id_answer1 { get; set; }

    public Nullable<int> id_answer2 { get; set; }

    public Nullable<int> id_answer3 { get; set; }

    public Nullable<int> id_answer4 { get; set; }

    public Nullable<bool> isMorphemes { get; set; }

    public Nullable<int> level { get; set; }

    public Nullable<bool> isComment { get; set; }

    public Nullable<int> id_training { get; set; }

}

}
