
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DatabaseFirst
{

using System;
    using System.Collections.Generic;
    
public partial class part1
{

    public int id { get; set; }

    public string name { get; set; }

    public Nullable<bool> odush { get; set; }

    public Nullable<bool> naricat { get; set; }

    public Nullable<bool> rod { get; set; }

    public Nullable<bool> sklonen { get; set; }

    public Nullable<bool> chislo { get; set; }

    public Nullable<bool> padezh { get; set; }

    public Nullable<bool> razryad { get; set; }

    public Nullable<bool> forma { get; set; }

    public Nullable<bool> stepsrav { get; set; }

    public Nullable<bool> prost { get; set; }

    public Nullable<bool> kolich { get; set; }

    public Nullable<bool> drob { get; set; }

    public Nullable<bool> razryadznach { get; set; }

    public Nullable<bool> lico { get; set; }

    public Nullable<bool> vid { get; set; }

    public Nullable<bool> spryazh { get; set; }

    public Nullable<bool> vozvrat { get; set; }

    public Nullable<bool> perehod { get; set; }

    public Nullable<bool> naklon { get; set; }

    public Nullable<bool> vremya { get; set; }

    public Nullable<bool> deistvit { get; set; }

    public Nullable<bool> neizmen { get; set; }

    public Nullable<bool> znacobraz { get; set; }

    public Nullable<bool> proizvodnost { get; set; }

    public Nullable<bool> sochinit { get; set; }

    public Nullable<bool> upotrebls { get; set; }

    public Nullable<bool> razryadpoznach { get; set; }

    public Nullable<bool> podrazryad { get; set; }

}

}
