
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DatabaseFirst
{

using System;
    using System.Collections.Generic;
    
public partial class progressUser
{

    public int id { get; set; }

    public string id_user { get; set; }

    public string word { get; set; }

    public Nullable<int> mark { get; set; }

    public Nullable<int> mark_add { get; set; }

}

}
