
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DatabaseFirst
{

using System;
    using System.Collections.Generic;
    
public partial class syll_mirror
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public syll_mirror()
    {

        this.themes = new HashSet<theme>();

    }


    public int id { get; set; }

    public Nullable<int> id_word { get; set; }

    public Nullable<int> id_answer1 { get; set; }

    public Nullable<int> id_answer2 { get; set; }

    public Nullable<int> id_answer3 { get; set; }

    public Nullable<int> id_answer4 { get; set; }

    public Nullable<int> level { get; set; }

    public Nullable<int> id_lexic { get; set; }

    public Nullable<bool> isMorphemes { get; set; }

    public Nullable<bool> isComment { get; set; }



    public virtual lexicAll lexicAll { get; set; }

    public virtual word word { get; set; }

    public virtual word word1 { get; set; }

    public virtual word word2 { get; set; }

    public virtual word word3 { get; set; }

    public virtual word word4 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<theme> themes { get; set; }

}

}
