
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DatabaseFirst
{

using System;
    using System.Collections.Generic;
    
public partial class Teacher
{

    public string Name { get; set; }

    public string Id { get; set; }

    public string Expr1 { get; set; }

    public string Email { get; set; }

}

}
