
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DatabaseFirst
{

using System;
    using System.Collections.Generic;
    
public partial class theme
{

    public int id_exercise { get; set; }

    public int id_part { get; set; }

    public int id_training { get; set; }



    public virtual part part { get; set; }

    public virtual syll_mirror syll_mirror { get; set; }

    public virtual training training { get; set; }

    public virtual training training1 { get; set; }

}

}
