
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DatabaseFirst
{

using System;
    using System.Collections.Generic;
    
public partial class word
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public word()
    {

        this.lexicologies = new HashSet<lexicology>();

        this.lexicologies1 = new HashSet<lexicology>();

        this.syll_mirror = new HashSet<syll_mirror>();

        this.syll_mirror1 = new HashSet<syll_mirror>();

        this.syll_mirror2 = new HashSet<syll_mirror>();

        this.syll_mirror3 = new HashSet<syll_mirror>();

        this.syll_mirror4 = new HashSet<syll_mirror>();

    }


    public int id { get; set; }

    public string word1 { get; set; }

    public string primary_form { get; set; }

    public Nullable<int> id_morphems { get; set; }

    public string phonetic { get; set; }

    public Nullable<int> id_morphology { get; set; }

    public Nullable<int> num_accent { get; set; }

    public string context { get; set; }

    public string morphems { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<lexicology> lexicologies { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<lexicology> lexicologies1 { get; set; }

    public virtual morphem morphem { get; set; }

    public virtual morphology morphology { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<syll_mirror> syll_mirror { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<syll_mirror> syll_mirror1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<syll_mirror> syll_mirror2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<syll_mirror> syll_mirror3 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<syll_mirror> syll_mirror4 { get; set; }

}

}
