
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DatabaseFirst
{

using System;
    using System.Collections.Generic;
    
public partial class wordsList
{

    public int id_exercise { get; set; }

    public int id_part { get; set; }

    public string word { get; set; }

    public string answer1_word { get; set; }

    public string answer2_word { get; set; }

    public string answer3_word { get; set; }

    public string answer4_word { get; set; }

    public Nullable<int> level { get; set; }

    public Nullable<int> answer2_id_morphology { get; set; }

    public Nullable<int> answer3_id_morphology { get; set; }

    public Nullable<int> answer4_id_morphology { get; set; }

    public string word_name { get; set; }

    public string answer1_name { get; set; }

    public string answer2_name { get; set; }

    public string answer3_name { get; set; }

    public string answer4_name { get; set; }

    public int id_training { get; set; }

}

}
