
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DatabaseFirst
{

using System;
    using System.Collections.Generic;
    
public partial class wordsView
{

    public int id { get; set; }

    public Nullable<int> id_part { get; set; }

    public int Expr1 { get; set; }

    public string word { get; set; }

    public Nullable<int> id_morphology { get; set; }

    public string name { get; set; }

}

}
